const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs'), assert = require('node:assert/strict'), path = require('node:path');
const url=process.env.QA_URL||'http://127.0.0.1:3000';
fs.mkdirSync('qa',{recursive:true});
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
 const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
 const check=name=>{checks.push(name);console.log('PASS '+name)};
 const ready=async()=>page.waitForFunction(()=>document.querySelector('#download')&&!document.querySelector('#download').disabled);
 const saved=async()=>{await page.waitForTimeout(220);await page.waitForFunction(()=>document.querySelector('#statusText').textContent==='자동 저장됨');return page.evaluate(()=>JSON.parse(localStorage.getItem('cutnote-state')))};
 const range=async(id,value)=>{await page.locator('#'+id).evaluate((el,v)=>{el.value=String(v);el.dispatchEvent(new Event('input',{bubbles:true}));},value);await saved();};
 const download=async(id,name)=>{const waiting=page.waitForEvent('download');await page.locator('#'+id).click();const result=await waiting;await result.saveAs(path.resolve('qa',name));return fs.readFileSync(path.resolve('qa',name));};
 const project=async(data)=>{await page.locator('#openImport').click();await page.locator('#jsonInput').setInputFiles({name:'project.json',mimeType:'application/json',buffer:Buffer.from(typeof data==='string'?data:JSON.stringify(data))});};
 const drag=async(x,y,dx,dy)=>{await page.locator('#preview').scrollIntoViewIfNeeded();const b=await page.locator('#preview').boundingBox();await page.mouse.move(b.x+b.width*x,b.y+b.height*y);await page.mouse.down();await page.mouse.move(b.x+b.width*(x+dx),b.y+b.height*(y+dy),{steps:5});await page.mouse.up();};
 try{
  await page.goto(url);await ready();await saved();
  assert.equal(await page.locator('#caption').inputValue(),'');assert.equal(await page.locator('#sampleGrid').count(),0);assert.equal(await page.locator('#photoSlot option').count(),1);assert.equal(await page.locator('#photoAfter').isDisabled(),true);check('optional empty text / removed samples / single-slot controls');
  const alpha=await page.evaluate(async()=>{const {stickerAssets}=await import('./assets.js');return ['glass-spark','glass-heart','glass-moon','bubble-sheet'].map(key=>{const c=stickerAssets[key].image,p=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let clear=0,visible=0;for(let i=3;i<p.length;i+=4){if(p[i]===0)clear++;else visible++;}return {key,clear,visible};});});assert.ok(alpha.every(a=>a.clear>1000&&a.visible>1000));check('four RGBA stickers have transparent backgrounds');
  assert.equal(await page.locator('[data-sticker]').count(),140);assert.equal(await page.locator('[data-template]').count(),6);check('140 stickers / 6 frames load');
  const photo=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=600;c.height=400;const x=c.getContext('2d');x.fillStyle='#cc573c';x.fillRect(0,0,300,400);x.fillStyle='#3c8caa';x.fillRect(300,0,300,400);x.fillStyle='white';x.fillRect(20,30,70,80);return c.toDataURL().split(',')[1]});
  const upload={name:'test-photo.png',mimeType:'image/png',buffer:Buffer.from(photo,'base64')};
  await page.locator('#imageInput').setInputFiles(upload);assert.equal((await saved()).images.length,1);
  await page.locator('#undoEdit').click();assert.equal((await saved()).images.length,0);
  await page.locator('#redoEdit').click();assert.equal((await saved()).images.length,1);check('photo upload undo / redo');
  await page.locator('[data-template="life-four"]').click();assert.equal((await saved()).templateId,'life-four');
  await page.locator('#undoEdit').click();assert.equal((await saved()).templateId,'camera-silver');
  await page.locator('#redoEdit').click();assert.equal((await saved()).ratio,'9:16');check('frame selection undo / redo');
  await page.locator('#photoSlot').selectOption('1');assert.equal(await page.locator('#photoZoom').isDisabled(),true);await page.locator('#replacePhoto').click();await page.locator('#slotImageInput').setInputFiles(upload);await saved();await range('photoZoom',1.5);assert.equal((await saved()).images[1].zoom,1.5);
  await range('photoRotate',30);assert.equal((await saved()).images[1].rotate,30);
  await page.locator('#photoAfter').click();assert.equal((await saved()).images[2].zoom,1.5);
  await page.locator('#removePhoto').click();assert.equal((await saved()).images[2],null);
  await page.locator('#undoEdit').click();assert.equal((await saved()).images[2].rotate,30);
  await page.locator('#replacePhoto').click();await page.locator('#slotImageInput').setInputFiles(upload);await saved();await page.locator('#undoEdit').click();assert.equal((await saved()).images[2].rotate,30);check('photo zoom / rotate / swap / remove / replace history');
  await page.locator('[data-sticker="heart"]').click();let s=await saved(),id=s.layers.at(-1).id;
  await range('stickerX',40);await range('stickerY',35);await range('stickerSize',28);await range('layerRotation',35);await range('layerOpacity',55);
  s=await saved();assert.deepEqual([s.layers.at(-1).x,s.layers.at(-1).y,s.layers.at(-1).size,s.layers.at(-1).rotation,s.layers.at(-1).opacity],[.4,.35,.28,35,.55]);
  await page.locator('#flipLayer').click();assert.equal((await saved()).layers.at(-1).flip,true);
  await page.locator('#duplicateLayer').click();s=await saved();assert.notEqual(s.layers.at(-1).id,id);const copy=s.layers.at(-1).id;
  await page.locator('#layerBackward').click();s=await saved();assert.equal(s.layers.at(-2).id,copy);
  await page.locator('#layerForward').click();s=await saved();assert.equal(s.layers.at(-1).id,copy);
  await page.locator('#removeSticker').click();assert.equal((await saved()).layers.at(-1).id,id);
  await page.locator('#undoEdit').click();assert.equal((await saved()).layers.at(-1).id,copy);check('sticker transforms / duplicate / order / delete / undo');
  await page.locator('#layerList').selectOption(copy);await page.locator('#preview').focus();let before=(await saved()).layers.at(-1).x;
  await page.keyboard.press('Shift+ArrowRight');assert.ok(Math.abs((await saved()).layers.at(-1).x-before-.02)<1e-9);
  await page.keyboard.press('Control+z');assert.equal((await saved()).layers.at(-1).x,before);
  await page.keyboard.press('Control+Shift+z');assert.ok((await saved()).layers.at(-1).x>before);check('keyboard movement / undo / redo');
  s=await saved();let l=s.layers.at(-1);await drag(l.x,l.y,.06,.04);assert.ok(Math.abs((await saved()).layers.at(-1).x-l.x-.06)<.01);check('canvas sticker dragging');
  await range('layerRotation',0);await range('stickerSize',20);s=await saved();l=s.layers.at(-1);
  const shape=await page.locator('[data-sticker="heart"] img').evaluate(img=>({w:img.naturalWidth,h:img.naturalHeight}));
  const scale=1080*l.size/Math.max(shape.w,shape.h),halfW=shape.w*scale/2,halfH=shape.h*scale/2;
  await drag(l.x+halfW/1080,l.y+halfH/1920,.025,.025);assert.ok((await saved()).layers.at(-1).size>.2);
  s=await saved();l=s.layers.at(-1);const scaledH=shape.h*1080*l.size/Math.max(shape.w,shape.h);
  await drag(l.x,l.y-(scaledH/2+32)/1920,.04,.01);assert.ok(Math.abs((await saved()).layers.at(-1).rotation)>5);check('canvas resize / rotate handles');
  await page.locator('#caption').fill('자유 편집\n테스트');await saved();await page.locator('#layerList').selectOption('caption');await range('stickerSize',8);await range('layerRotation',45);await range('stickerX',55);await range('stickerY',65);s=await saved();assert.ok(Math.abs(s.fontSize-86.4)<1);assert.equal(s.captionRotation,45);
  await drag(.55,.65,.05,.05);assert.ok(Math.abs((await saved()).captionX-.6)<.01);check('caption resize / rotation / rotated text dragging');
  await page.locator('#layerList').selectOption('frame');await range('stickerSize',85);await range('layerRotation',25);await range('stickerX',40);await range('stickerY',45);
  await drag(.15,.15,.05,.05);s=await saved();assert.ok(Math.abs(s.frameX-.45)<.01);assert.equal(s.frameRotation,25);check('frame resize / rotation / dragging after rotation');
  await page.locator('#customSticker').setInputFiles({...upload,name:'my "sticker".png'});s=await saved();assert.ok(s.layers.at(-1).dataUrl);check('custom image sticker upload');
  await page.locator('#templateName').fill('QA template');await page.locator('#saveTemplate').click();s=await saved();const tid=s.templateId;assert.ok(tid.startsWith('user-'));
  await range('layerRotation',75);await page.locator('#updateTemplate').click();await saved();
  await page.locator('[data-template="rec-original"]').click();await saved();await page.locator(`[data-template="${tid}"]`).click();s=await saved();assert.equal(s.layers.at(-1).rotation,75);
  await page.reload();await ready();s=await saved();assert.equal(s.templateId,tid);assert.equal(s.layers.at(-1).rotation,75);assert.ok(s.images[0].dataUrl);
  await page.locator(`[data-template="${tid}"]`).click();await saved();await page.locator('#deleteTemplate').click();await saved();assert.equal(await page.locator(`[data-template="${tid}"]`).count(),0);
  await page.locator('#undoEdit').click();await saved();assert.equal(await page.locator(`[data-template="${tid}"]`).count(),1);check('template CRUD / custom asset reload / undo template deletion');
  const backup=JSON.parse((await download('exportJson','project.json')).toString());assert.equal(backup.version,2);
  await page.locator('#caption').fill('changed');await saved();await project(backup);await page.waitForFunction(()=>!document.querySelector('#importDialog').open);s=await saved();assert.equal(s.caption,backup.state.caption);assert.deepEqual(s.layers,backup.state.layers);check('JSON roundtrip images / transformations / templates');
  for(const broken of ['{broken',{version:2}, {...backup,state:{...backup.state,layers:[{...backup.state.layers[0],opacity:2}]}},{...backup,state:{...backup.state,fontSize:'bad'}},{...backup,templates:[{...backup.templates[0],layers:null}]},{...backup,state:{...backup.state,images:[{...backup.state.images[0],dataUrl:'data:image/png;base64,broken'}]}}]){
   const before=await saved();await project(broken);await page.waitForFunction(()=>document.querySelector('#jsonError').textContent.includes('기존 작업은 유지됩니다'));assert.deepEqual(await saved(),before);await page.locator('#importDialog .dialog-close').click();
  }check('6 invalid / corrupt backups preserve existing work');
  const stable=await saved();await page.evaluate(()=>{window.qaSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='cutnote-templates')throw new DOMException('Quota exceeded','QuotaExceededError');return window.qaSetItem.call(this,k,v);}});
  await project({...backup,state:{...backup.state,caption:'must not replace'}});await page.waitForFunction(()=>document.querySelector('#jsonError').textContent.includes('기존 작업은 유지됩니다'));assert.deepEqual(await saved(),stable);await page.locator('#importDialog .dialog-close').click();
  await page.evaluate(()=>{Storage.prototype.setItem=window.qaSetItem;delete window.qaSetItem});check('storage failure preserves project during import');
  await page.locator('#imageInput').setInputFiles({name:'bad.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg/>')});assert.ok((await page.locator('#fileError').textContent()).includes('PNG'));assert.deepEqual(await saved(),stable);check('unsupported image rejected without replacing work');
  for(const [ratio,w,h] of [['1:1',1080,1080],['4:5',1080,1350],['9:16',1080,1920]]){
   await page.locator(`[data-ratio="${ratio}"]`).click();await saved();const png=await download('download',ratio.replace(':','x')+'.png');assert.equal(png.readUInt32BE(16),w);assert.equal(png.readUInt32BE(20),h);
   await page.locator('#layerList').evaluate(el=>{el.selectedIndex=-1;el.dispatchEvent(new Event('change',{bubbles:true}))});
   const preview=await page.locator('#preview').evaluate(c=>c.toDataURL().split(',')[1]);assert.deepEqual(png,Buffer.from(preview,'base64'));
  }check('3 PNG sizes / exact preview pixels / no selection exported');
  await page.locator('#preview').screenshot({path:'qa/edited-canvas.png'});
  for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow ${width}`);if(width===390)await page.screenshot({path:'qa/mobile.png',fullPage:true});}check('desktop / tablet / mobile horizontal overflow');
  assert.deepEqual(errors,[]);check('no browser runtime errors');
  fs.writeFileSync('qa/results.json',JSON.stringify({url,checks,errors,at:new Date().toISOString()},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
