const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
 const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
 const pass=n=>{checks.push(n);console.log('PASS '+n)};
 const saved=async()=>{await page.waitForTimeout(250);await page.waitForFunction(()=>document.querySelector('#statusText').textContent==='자동 저장됨');return page.evaluate(()=>JSON.parse(localStorage.getItem('cutnote-state')))};
 const range=async(id,v)=>{await page.locator('#'+id).evaluate((el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}))},v);return saved()};
 const ready=async()=>page.waitForFunction(()=>!document.querySelector('#download').disabled);
 const importData=async data=>{await page.locator('#openImport').click();await page.locator('#jsonInput').setInputFiles({name:'text.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});};
 try{
  await page.goto(process.env.QA_URL||'http://localhost:3000');await ready();let s=await saved();
  assert.deepEqual(s.texts,[]);assert.ok(await page.locator('#textEditor').isHidden());assert.equal(await page.locator('#textPosition').count(),0);assert.ok(!(await page.locator('body').innerText()).includes('선택 사항'));pass('collapsed editor / no required text / preset position buttons removed');
  await page.locator('#addText').click();await page.locator('#caption').fill('첫 번째 문구');await page.locator('#fontFamily').selectOption('Nanum Pen Script');await range('textX',30);await range('textY',35);await range('fontSize',85);await range('textRotation',20);s=await saved();const first=structuredClone(s.texts[0]);
  await page.locator('#addText').click();await page.locator('#caption').fill('두 번째 문구');await page.locator('#fontFamily').selectOption('Noto Serif KR');await range('textX',65);await range('textY',70);s=await saved();const second=s.texts[1];assert.deepEqual(s.texts[0],first);assert.notEqual(first.id,second.id);pass('multiple independent text content / fonts / size / free coordinates / rotation');
  for(const font of await page.locator('#fontFamily option').evaluateAll(es=>es.map(e=>e.value))){await page.locator('#fontFamily').selectOption(font);await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(500);assert.equal(await page.locator('#fontStatus').textContent(),'');assert.ok(await page.evaluate(f=>document.fonts.check(`${f==='Gaegu'?700:400} 64px "${f}"`,'두 번째 문구'),font));}pass('all six Korean fonts load');
  await page.locator('#textList').selectOption(first.id);await page.locator('#duplicateText').click();s=await saved();assert.equal(s.texts.length,3);assert.equal(s.texts[2].fontFamily,first.fontFamily);await page.locator('#deleteText').click();assert.equal((await saved()).texts.length,2);await page.locator('#undoEdit').click();assert.equal((await saved()).texts.length,3);await page.locator('#redoEdit').click();assert.equal((await saved()).texts.length,2);pass('text duplicate / delete / undo / redo');
  await page.locator('#textList').selectOption(first.id);await page.locator('#preview').scrollIntoViewIfNeeded();const box=await page.locator('#preview').boundingBox();await page.mouse.move(box.x+box.width*.30,box.y+box.height*.35);await page.mouse.down();await page.mouse.move(box.x+box.width*.38,box.y+box.height*.40,{steps:5});await page.mouse.up();s=await saved();assert.ok(Math.abs(s.texts[0].captionX-.38)<.01);assert.ok(Math.abs(s.texts[0].captionY-.4)<.01);await page.keyboard.press('Shift+ArrowRight');s=await saved();assert.ok(Math.abs(s.texts[0].captionX-.4)<.01);assert.equal(s.texts[1].captionX,.65);pass('rotated text canvas selection / drag / keyboard independent movement');
  await page.locator('#collapseText').click();assert.ok(await page.locator('#textEditor').isHidden());await page.locator('#layerList').selectOption(first.id);assert.ok(await page.locator('#textEditor').isVisible());pass('collapse / select existing text expands editor');
  const beforeReload=structuredClone((await saved()).texts);await page.reload();await ready();assert.deepEqual((await saved()).texts,beforeReload);pass('all text settings survive reload');
  await page.locator('#templateName').fill('여러 문구');await page.locator('#saveTemplate').click();s=await saved();const tid=s.templateId;await page.locator('#addText').click();await saved();await page.locator(`[data-template="${tid}"]`).click();assert.deepEqual((await saved()).texts,beforeReload);pass('user template restores multiple text layers');
  const dl=page.waitForEvent('download');await page.locator('#exportJson').click();const result=await dl;const path=await result.path();const backup=JSON.parse(fs.readFileSync(path,'utf8'));
  await page.locator('#addText').click();await saved();await importData(backup);await page.waitForFunction(()=>!document.querySelector('#importDialog').open);assert.deepEqual((await saved()).texts,backup.state.texts);pass('JSON restores all text settings');
  for(const texts of [[{...first,fontFamily:'invalid'}],[first,first],[{...first,captionX:'bad'}]]){const old=(await saved()).texts;await importData({...backup,state:{...backup.state,texts}});await page.waitForFunction(()=>document.querySelector('#jsonError').textContent.includes('기존 작업은 유지됩니다'));assert.deepEqual((await saved()).texts,old);await page.locator('#importDialog .dialog-close').click();}pass('invalid fonts / duplicate text IDs / corrupt coordinates preserve existing work');
  const legacy={...backup,state:{...backup.state,caption:'예전 문구',captionX:.22,captionY:.33,captionRotation:17,fontSize:78,textColor:'#112233'}};delete legacy.state.texts;await importData(legacy);await page.waitForFunction(()=>!document.querySelector('#importDialog').open);s=await saved();assert.equal(s.texts.length,1);assert.deepEqual([s.texts[0].caption,s.texts[0].captionX,s.texts[0].captionY,s.texts[0].captionRotation,s.texts[0].fontFamily],['예전 문구',.22,.33,17,'Gaegu']);pass('legacy single caption migration preserves appearance');
  await importData(backup);await page.waitForFunction(()=>!document.querySelector('#importDialog').open);await saved();
  for(const [ratio,w,h] of [['1:1',1080,1080],['4:5',1080,1350],['9:16',1080,1920]]){
   await page.locator(`[data-ratio="${ratio}"]`).click();await saved();await page.locator('#layerList').evaluate(el=>{el.selectedIndex=-1;el.dispatchEvent(new Event('change',{bubbles:true}))});
   const dl=page.waitForEvent('download');await page.locator('#download').click();const d=await dl;const png=fs.readFileSync(await d.path());assert.equal(png.readUInt32BE(16),w);assert.equal(png.readUInt32BE(20),h);assert.deepEqual(png,Buffer.from(await page.locator('#preview').evaluate(c=>c.toDataURL().split(',')[1]),'base64'));
  }pass('multiple text PNG exports match preview at all three resolutions');
  await page.locator('#layerList').selectOption(first.id);await page.locator('#caption').scrollIntoViewIfNeeded();await page.screenshot({path:'qa/text-desktop.png'});
  for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if(width===390){await page.locator('#textEditor').scrollIntoViewIfNeeded();await page.screenshot({path:'qa/text-mobile.png'});}}pass('desktop / tablet / mobile without horizontal overflow');
  assert.deepEqual(errors,[]);pass('no browser runtime errors');fs.writeFileSync('qa/text-results.json',JSON.stringify({checks,errors},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
