const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const fs=require('fs'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:900},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{await page.goto(process.env.QA_URL||'http://localhost:3000');await page.waitForFunction(()=>!document.querySelector('#download').disabled);await page.screenshot({path:'qa/dark-desktop.png',fullPage:true});console.log('height',await page.evaluate(()=>({scroll:document.documentElement.scrollHeight,view:innerHeight})));assert.equal(await page.title(),'CUT&NOTE');assert.equal(await page.locator('.brand').innerText(),'CUT&NOTE');assert.equal(await page.locator('link[rel=icon]').getAttribute('href'),await page.locator('.brand-mark').getAttribute('src'));assert.equal(await page.locator('#page-title').textContent(),'STUDIO');assert.equal(await page.locator('[data-mobile=canvas]').count(),0);assert.equal(await page.locator('[data-tool=canvas]').count(),0);assert.equal(await page.locator('.control-panel .panel-heading').count(),0);assert.equal(await page.locator('.canvas-settings #ratios').count(),1);assert.equal(await page.locator('.library-tabs').count(),1);assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1));await page.locator('.template-pager button[aria-label="다음 템플릿"]').click();assert.ok((await page.locator('.template-pager span').textContent()).startsWith('2'));await page.locator('.template-pager button[aria-label="이전 템플릿"]').click();
 await page.locator('[data-pane=stickers]').click();await page.locator('.carousel-nav button').filter({hasText:'크롬'}).click();assert.ok(await page.locator('[data-sticker]:visible').count()<40);await page.locator('[data-sticker=heart]').click();assert.equal(await page.locator('[data-pane=layers]').getAttribute('aria-selected'),'true');
 await page.locator('[data-tool=text] summary').click();await page.locator('#addText').click();await page.locator('#caption').fill('CHROME / 03');await page.locator('#fontFamily').selectOption('Noto Sans KR');
 await page.locator('[data-pane=templates]').click();while(await page.locator('.template-pager button[aria-label="이전 템플릿"]').isEnabled())await page.locator('.template-pager button[aria-label="이전 템플릿"]').click();await page.locator('#buildOwn').click();await page.waitForTimeout(300);assert.equal(await page.locator('#backgroundColor').inputValue(),'#ffffff');await page.screenshot({path:'qa/brand-blank-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:900});await page.screenshot({path:'qa/brand-blank-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:900});await page.locator('#addSlot').click();await page.locator('#addSlot').click();
 const image=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=500;c.height=400;const x=c.getContext('2d');x.fillStyle='#31313b';x.fillRect(0,0,500,400);x.fillStyle='#aaaab8';x.fillRect(50,40,400,320);x.fillStyle='#121218';x.font='bold 50px sans-serif';x.fillText('CHROME',120,220);return c.toDataURL().split(',')[1]});await page.locator('#imageInput').setInputFiles({name:'chrome.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')});
 await page.locator('[data-tool=photo] summary .help-icon').hover();assert.equal(await page.locator('#helpBalloon').isVisible(),true);await page.keyboard.press('Escape');await page.locator('[data-tool=photo] summary .help-icon').focus();await page.keyboard.press('Escape');assert.equal(await page.locator('#helpBalloon').isVisible(),false);
 await page.locator('[data-pane=templates]').click();while(await page.locator('.template-pager button[aria-label="이전 템플릿"]').isEnabled())await page.locator('.template-pager button[aria-label="이전 템플릿"]').click();await page.locator('[data-template=contact-grid]').click();await page.locator('[data-pane=stickers]').click();await page.locator('.carousel-nav button').filter({hasText:'크롬'}).click();await page.locator('[data-sticker=heart]').click();
 await page.locator('[data-tool=text] summary').click();await page.locator('#addText').click();await page.locator('#caption').fill('CHROME / 03');await page.locator('#fontFamily').selectOption('Noto Sans KR');
 for(const format of ['png','jpg','pdf']){await page.locator('#exportFormat').selectOption(format);const d=page.waitForEvent('download');await page.locator('#download').click();await(await d).saveAs('qa/dark.'+format);}
 const d=page.waitForEvent('download');await page.locator('#exportJson').click();await(await d).saveAs('qa/dark.json');const data=JSON.parse(fs.readFileSync('qa/dark.json'));assert.equal(data.state.texts.length,1);assert.equal(data.state.layers.length,1);
 await page.locator('#openImport').click();await page.locator('#jsonInput').setInputFiles('qa/dark.json');await page.waitForTimeout(400);assert.equal(await page.locator('#importDialog').isVisible(),false);
 await page.evaluate(()=>document.activeElement.blur());await page.evaluate(()=>document.querySelectorAll('.control-panel,.template-panel').forEach(p=>p.scrollTop=0));await page.waitForTimeout(250);await page.screenshot({path:'qa/dark-editor.png',fullPage:true});
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(width===390){await page.locator('[data-mobile=library]').click();await page.locator('[data-pane=stickers]').click();await page.waitForTimeout(250);await page.screenshot({path:'qa/dark-mobile.png',fullPage:true});await page.locator('[data-mobile=text]').click();assert.equal(await page.locator('#caption').isVisible(),true);}}
 assert.deepEqual(errors,[]);console.log('PASS dark UI tabs / sticker filters / auto layer selection / text / custom slots / help hover-focus-Escape / exports / JSON / responsive / no runtime errors');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});

